Commit

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -809,6 +809,8 @@ Optional Features:
   --enable-sdl            enable the use of the SDL library. (default auto)
   --enable-svgawin        enable the use of the SVGAWIN library. (default
                           auto)
+  --enable-kraw           enable the use of the KRAW keyboard library.
+                          (default auto)
   --enable-debugger       enable the emulator debugger (default no)
   --enable-compress       enable the compression of the executable (default
                           no)
@@ -4819,6 +4821,113 @@ fi
 CONF_LIB_SVGAWIN=$ac_lib_svgawin
 
 
+# Check whether --enable-kraw or --disable-kraw was given.
+if test "${enable_kraw+set}" = set; then
+  enableval="$enable_kraw"
+  ac_lib_kraw=$withval
+else
+  ac_lib_kraw=auto
+
+fi;
+if test $ac_lib_kraw = auto; then
+	if test $ac_host = unix; then
+		echo "$as_me:$LINENO: checking for KRAW keyboard interface" >&5
+echo $ECHO_N "checking for KRAW keyboard interface... $ECHO_C" >&6
+		cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <sys/kd.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+int dummy = K_MEDIUMRAW;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_lib_kraw=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_lib_kraw=no
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+		echo "$as_me:$LINENO: result: $ac_lib_kraw" >&5
+echo "${ECHO_T}$ac_lib_kraw" >&6
+	else
+		ac_lib_kraw=no
+	fi
+elif test $ac_lib_fb = yes; then
+	echo "$as_me:$LINENO: checking for KRAW keyboard interface" >&5
+echo $ECHO_N "checking for KRAW keyboard interface... $ECHO_C" >&6
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <sys/kd.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+int dummy = K_MEDIUMRAW;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+{ { echo "$as_me:$LINENO: error: The KRAW keyboard interface is missing" >&5
+echo "$as_me: error: The KRAW keyboard interface is missing" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+	echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+fi
+if test $ac_lib_kraw = yes; then
+	ac_lib="$ac_lib KRAW"
+fi
+CONF_LIB_KRAW=$ac_lib_kraw
+
+
 # Check whether --enable-debugger or --disable-debugger was given.
 if test "${enable_debugger+set}" = set; then
   enableval="$enable_debugger"
@@ -5577,6 +5686,7 @@ s,@SDLCFLAGS@,$SDLCFLAGS,;t t
 s,@SDLLIBS@,$SDLLIBS,;t t
 s,@CONF_LIB_SDL@,$CONF_LIB_SDL,;t t
 s,@CONF_LIB_SVGAWIN@,$CONF_LIB_SVGAWIN,;t t
+s,@CONF_LIB_KRAW@,$CONF_LIB_KRAW,;t t
 s,@CONF_DEBUGGER@,$CONF_DEBUGGER,;t t
 s,@UPX@,$UPX,;t t
 s,@TOUCH@,$TOUCH,;t t
