Commit

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -806,6 +806,7 @@ Optional Features:
                           auto)
   --enable-fb             enable the use of the Frame Buffer library. (default
                           auto)
+  --enable-alsa           enable the use of the ALSA library. (default auto)
   --enable-oss            enable the use of the OSS library. (default auto)
   --enable-pthread        enable the use of the pthread library (default auto)
   --enable-slang          enable the use of the sLang library (default auto)
@@ -4064,6 +4065,123 @@ fi
 CONF_LIB_FB=$ac_lib_fb
 
 
+# Check whether --enable-alsa or --disable-alsa was given.
+if test "${enable_alsa+set}" = set; then
+  enableval="$enable_alsa"
+  ac_lib_alsa=$enableval
+else
+  ac_lib_alsa=auto
+
+fi;
+if test $ac_lib_alsa = auto; then
+	if test $ac_host = unix; then
+		echo "$as_me:$LINENO: checking for ALSA" >&5
+echo $ECHO_N "checking for ALSA... $ECHO_C" >&6
+		cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <alsa/asoundlib.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+				#if SND_LIB_VERSION < ((0<<16)|(9<<8)|0)
+				choke me
+				#endif
+				int dummy = SND_PCM_FORMAT_S16_LE;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_lib_alsa=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_lib_alsa=no
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+		echo "$as_me:$LINENO: result: $ac_lib_alsa" >&5
+echo "${ECHO_T}$ac_lib_alsa" >&6
+	else
+		ac_lib_alsa=no
+	fi
+elif test $ac_lib_alsa = yes; then
+	echo "$as_me:$LINENO: checking for ALSA" >&5
+echo $ECHO_N "checking for ALSA... $ECHO_C" >&6
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <alsa/asoundlib.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+			#if SND_LIB_VERSION < ((0<<16)|(9<<8)|0)
+			choke me
+			#endif
+			int dummy = SND_PCM_FORMAT_S16_LE;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+{ { echo "$as_me:$LINENO: error: The ALSA library is missing or too old" >&5
+echo "$as_me: error: The ALSA library is missing or too old" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+	echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+fi
+if test $ac_lib_alsa = yes; then
+	ac_lib="$ac_lib ALSA"
+fi
+CONF_LIB_ALSA=$ac_lib_alsa
+
+
 # Check whether --enable-oss or --disable-oss was given.
 if test "${enable_oss+set}" = set; then
   enableval="$enable_oss"
@@ -4491,6 +4609,7 @@ if test $ac_lib_sdl = auto; then
 	else
 		if test -z ${host_alias} ; then
 			for ac_prog in sdl-config
+
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -4529,11 +4648,10 @@ fi
 
   test -n "$SDLCONFIG" && break
 done
-test -n "$SDLCONFIG" || SDLCONFIG="no
-			"
 
 		else
 			for ac_prog in ${host_alias}-sdl-config
+
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -4572,22 +4690,21 @@ fi
 
   test -n "$SDLCONFIG" && break
 done
-test -n "$SDLCONFIG" || SDLCONFIG="no
-			"
 
 		fi
-		if test ! $SDLCONFIG = no; then
+		if test -z $SDLCONFIG; then
+			ac_lib_sdl=no
+		else
 			SDLCFLAGS=`$SDLCONFIG --cflags`
 			SDLLIBS=`$SDLCONFIG --libs`
-		fi
-		echo "$as_me:$LINENO: checking for SDL_Init in -lSDL" >&5
+			echo "$as_me:$LINENO: checking for SDL_Init in -lSDL" >&5
 echo $ECHO_N "checking for SDL_Init in -lSDL... $ECHO_C" >&6
 if test "${ac_cv_lib_SDL_SDL_Init+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lSDL $SDLLIBS
-		 $LIBS"
+			 $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
@@ -4642,10 +4759,12 @@ else
   ac_lib_sdl=no
 fi
 
+		fi
 	fi
 elif test $ac_lib_sdl = yes; then
 	if test -z ${host_alias} ; then
 		for ac_prog in sdl-config
+
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -4684,11 +4803,10 @@ fi
 
   test -n "$SDLCONFIG" && break
 done
-test -n "$SDLCONFIG" || SDLCONFIG="no
-		"
 
 	else
 		for ac_prog in ${host_alias}-sdl-config
+
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -4727,14 +4845,15 @@ fi
 
   test -n "$SDLCONFIG" && break
 done
-test -n "$SDLCONFIG" || SDLCONFIG="no
-		"
 
 	fi
-	if test ! $SDLCONFIG = no; then
+	if test -z $SDLCONFIG ; then
+		{ { echo "$as_me:$LINENO: error: The sdl-config tool is missing" >&5
+echo "$as_me: error: The sdl-config tool is missing" >&2;}
+   { (exit 1); exit 1; }; }
+	else
 		SDLCFLAGS=`$SDLCONFIG --cflags`
 		SDLLIBS=`$SDLCONFIG --libs`
-	fi
 
 echo "$as_me:$LINENO: checking for SDL_Init in -lSDL" >&5
 echo $ECHO_N "checking for SDL_Init in -lSDL... $ECHO_C" >&6
@@ -4743,7 +4862,7 @@ if test "${ac_cv_lib_SDL_SDL_Init+set}" = set; then
 else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lSDL $SDLLIBS
-	 $LIBS"
+		 $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
@@ -4805,6 +4924,7 @@ echo "$as_me: error: The SDL library is missing" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
+	fi
 fi
 if test $ac_lib_sdl = yes; then
 	ac_lib="$ac_lib SDL"
@@ -5692,6 +5812,7 @@ s,@CONF_CFLAGS_ARCH@,$CONF_CFLAGS_ARCH,;t t
 s,@CONF_EMU@,$CONF_EMU,;t t
 s,@CONF_LIB_SVGALIB@,$CONF_LIB_SVGALIB,;t t
 s,@CONF_LIB_FB@,$CONF_LIB_FB,;t t
+s,@CONF_LIB_ALSA@,$CONF_LIB_ALSA,;t t
 s,@CONF_LIB_OSS@,$CONF_LIB_OSS,;t t
 s,@CONF_LIB_PTHREAD@,$CONF_LIB_PTHREAD,;t t
 s,@CONF_LIB_SLANG@,$CONF_LIB_SLANG,;t t
