Commit

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -272,7 +272,7 @@ PACKAGE_VERSION='source'
 PACKAGE_STRING='advance source'
 PACKAGE_BUGREPORT=''
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os ASMFLAGS CFLAGS_BUILD EXE CONF_HOST EXE_BUILD CONF_BUILD CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S AR ac_ct_AR RC ac_ct_RC RM CP MKDIR ECHO TAR GZIP ZIP CC_BUILD CXX_BUILD CONF_DEBUG CONF_CFLAGS_OPT CONF_LDFLAGS ASM CONF_CFLAGS_ARCH CONF_EMU CONF_DEBUGGER ZLIBS CONF_LIB_SVGALIB CONF_LIB_FB CONF_LIB_ALSA CONF_LIB_OSS CONF_LIB_PTHREAD CONF_LIB_SLANG ac_lib_sdl_config SDLCFLAGS SDLLIBS CONF_LIB_SDL CONF_LIB_SVGAWIN CONF_LIB_KRAW CONF LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os ASMFLAGS CFLAGS_BUILD EXE CONF_HOST EXE_BUILD CONF_BUILD CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S AR ac_ct_AR RC ac_ct_RC RM CP MKDIR ECHO TAR GZIP ZIP CC_BUILD CXX_BUILD CONF_DEBUG CONF_CFLAGS_OPT CONF_LDFLAGS ASM CONF_CFLAGS_ARCH CONF_EMU CONF_DEBUGGER ZLIBS CONF_LIB_SVGALIB CONF_LIB_FB CONF_LIB_ALSA CONF_LIB_OSS CONF_LIB_PTHREAD CONF_LIB_SLANG ac_lib_sdl_config SDLCFLAGS SDLLIBS CONF_LIB_SDL CONF_LIB_SVGAWIN CONF_LIB_KRAW CONF_LIB_MRAW CONF LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -832,8 +832,10 @@ Optional Features:
   --enable-sdl            enable the use of the SDL library. (default auto)
   --enable-svgawin        enable the use of the SVGAWIN library. (default
                           auto)
-  --enable-kraw           enable the use of the KRAW keyboard library.
-                          (default auto)
+  --enable-kraw           enable the use of the RAW keyboard library. (default
+                          auto)
+  --enable-mraw           enable the use of the RAW mouse library. (default
+                          auto)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -5322,8 +5324,8 @@ else
 
 fi;
 if test $ac_lib_kraw = auto; then
-	echo "$as_me:$LINENO: checking for KRAW keyboard interface" >&5
-echo $ECHO_N "checking for KRAW keyboard interface... $ECHO_C" >&6
+	echo "$as_me:$LINENO: checking for RAW keyboard interface" >&5
+echo $ECHO_N "checking for RAW keyboard interface... $ECHO_C" >&6
 	cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -5365,8 +5367,8 @@ rm -f conftest.$ac_objext conftest.$ac_ext
 	echo "$as_me:$LINENO: result: $ac_lib_kraw" >&5
 echo "${ECHO_T}$ac_lib_kraw" >&6
 elif test $ac_lib_kraw = yes; then
-	echo "$as_me:$LINENO: checking for KRAW keyboard interface" >&5
-echo $ECHO_N "checking for KRAW keyboard interface... $ECHO_C" >&6
+	echo "$as_me:$LINENO: checking for RAW keyboard interface" >&5
+echo $ECHO_N "checking for RAW keyboard interface... $ECHO_C" >&6
 	cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -5415,6 +5417,109 @@ if test $ac_lib_kraw = yes; then
 	ac_lib_keyboard=yes
 fi
 CONF_LIB_KRAW=$ac_lib_kraw
+
+
+# Check whether --enable-mraw or --disable-mraw was given.
+if test "${enable_mraw+set}" = set; then
+  enableval="$enable_mraw"
+  ac_lib_mraw=$enableval
+else
+  ac_lib_mraw=auto
+
+fi;
+if test $ac_lib_mraw = auto; then
+	echo "$as_me:$LINENO: checking for RAW mouse interface" >&5
+echo $ECHO_N "checking for RAW mouse interface... $ECHO_C" >&6
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/ioctl.h>
+int
+main ()
+{
+
+			int dummy = TIOCMSET;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_lib_mraw=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_lib_mraw=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+	echo "$as_me:$LINENO: result: $ac_lib_mraw" >&5
+echo "${ECHO_T}$ac_lib_mraw" >&6
+elif test $ac_lib_mraw = yes; then
+	echo "$as_me:$LINENO: checking for RAW mouse interface" >&5
+echo $ECHO_N "checking for RAW mouse interface... $ECHO_C" >&6
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/ioctl.h>
+int
+main ()
+{
+
+			int dummy = TIOCMSET;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+{ { echo "$as_me:$LINENO: error: the KRAW keyboard interface is missing" >&5
+echo "$as_me: error: the KRAW keyboard interface is missing" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+	echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+fi
+if test $ac_lib_mraw = yes; then
+	ac_lib="$ac_lib MRAW"
+fi
+CONF_LIB_MRAW=$ac_lib_mraw
 
 
 # Notify that ./configure was runned
@@ -6118,6 +6223,7 @@ s,@SDLLIBS@,$SDLLIBS,;t t
 s,@CONF_LIB_SDL@,$CONF_LIB_SDL,;t t
 s,@CONF_LIB_SVGAWIN@,$CONF_LIB_SVGAWIN,;t t
 s,@CONF_LIB_KRAW@,$CONF_LIB_KRAW,;t t
+s,@CONF_LIB_MRAW@,$CONF_LIB_MRAW,;t t
 s,@CONF@,$CONF,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
