Commit

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1267,15 +1267,27 @@ host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 case "$host" in
 	*-*-linux*)
 		ac_host=linux
+		ASMFLAGS="-f elf"
+
+		CFLAGS_BUILD="-O0 -DCOMPILER_TARGET_GNUC -DOBJ_TARGET_ELF"
+
 
 	;;
 	*-*-cygwin* | *-*-mingw32*)
 		ac_host=windows
+		ASMFLAGS="-f coff"
+
+		CFLAGS_BUILD="-O0 -DCOMPILER_TARGET_GNUC -DOBJ_TARGET_COFF"
+
 		EXE=.exe
 
 	;;
 	*-*-msdos*)
 		ac_host=dos
+		ASMFLAGS="-f coff"
+
+		CFLAGS_BUILD="-O0 -DCOMPILER_TARGET_GNUC -DOBJ_TARGET_COFF"
+
 		EXE=.exe
 
 	;;
@@ -1314,6 +1326,9 @@ CONF_BUILD=$ac_build
 
 if test -z "$CFLAGS" ; then
 	CFLAGS="-O3 -fomit-frame-pointer -fstrict-aliasing -Wall -Wno-sign-compare -Wno-unused"
+fi
+if test -z "$LDFLAGS" ; then
+	LDFLAGS="-s"
 fi
 
 # Checks for programs.
@@ -2476,6 +2491,17 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL}'
 
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
+echo "$as_me:$LINENO: checking whether ln -s works" >&5
+echo $ECHO_N "checking whether ln -s works... $ECHO_C" >&6
+LN_S=$as_ln_s
+if test "$LN_S" = "ln -s"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me:$LINENO: result: no, using $LN_S" >&5
+echo "${ECHO_T}no, using $LN_S" >&6
+fi
+
 if test -n "$ac_tool_prefix"; then
   for ac_prog in ar
   do
@@ -2648,6 +2674,166 @@ done
   RC=$ac_ct_RC
 fi
 
+for ac_prog in rm
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_RM+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$RM"; then
+  ac_cv_prog_RM="$RM" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_RM="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+RM=$ac_cv_prog_RM
+if test -n "$RM"; then
+  echo "$as_me:$LINENO: result: $RM" >&5
+echo "${ECHO_T}$RM" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$RM" && break
+done
+
+for ac_prog in cp
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_CP+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$CP"; then
+  ac_cv_prog_CP="$CP" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_CP="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+CP=$ac_cv_prog_CP
+if test -n "$CP"; then
+  echo "$as_me:$LINENO: result: $CP" >&5
+echo "${ECHO_T}$CP" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$CP" && break
+done
+
+for ac_prog in mkdir
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_MKDIR+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$MKDIR"; then
+  ac_cv_prog_MKDIR="$MKDIR" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_MKDIR="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+MKDIR=$ac_cv_prog_MKDIR
+if test -n "$MKDIR"; then
+  echo "$as_me:$LINENO: result: $MKDIR" >&5
+echo "${ECHO_T}$MKDIR" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$MKDIR" && break
+done
+
+for ac_prog in echo
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_ECHO+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$ECHO"; then
+  ac_cv_prog_ECHO="$ECHO" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_ECHO="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+ECHO=$ac_cv_prog_ECHO
+if test -n "$ECHO"; then
+  echo "$as_me:$LINENO: result: $ECHO" >&5
+echo "${ECHO_T}$ECHO" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$ECHO" && break
+done
+
 for ac_prog in tar
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -2726,6 +2912,46 @@ echo "${ECHO_T}no" >&6
 fi
 
   test -n "$GZIP" && break
+done
+
+for ac_prog in zip
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_ZIP+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$ZIP"; then
+  ac_cv_prog_ZIP="$ZIP" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_ZIP="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+ZIP=$ac_cv_prog_ZIP
+if test -n "$ZIP"; then
+  echo "$as_me:$LINENO: result: $ZIP" >&5
+echo "${ECHO_T}$ZIP" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$ZIP" && break
 done
 
 for ac_prog in nasm
@@ -3126,6 +3352,13 @@ echo "$as_me: error: The zlib library is required" >&2;}
 
 fi
 
+if test $ac_host = windows; then
+	ZLIBS="-static -lz"
+else
+	ZLIBS="-lz"
+fi
+ZLIBS=$ZLIBS
+
 
 # Checks for header files.
 # Checks for typedefs, structures, and compiler characteristics.
@@ -3154,40 +3387,40 @@ if test $ac_with_emu = auto; then
 fi
 if test $ac_with_emu = mame -o $ac_with_emu = neomame -o $ac_with_emu = cpmame; then
 	if test ! -f $srcdir/src/mame.mak ; then
-		{ { echo "$as_me:$LINENO: error: You need the MAME source in the src/ directory" >&5
-echo "$as_me: error: You need the MAME source in the src/ directory" >&2;}
+		{ { echo "$as_me:$LINENO: error: You need the MAME source in the $srcdir/src/ directory" >&5
+echo "$as_me: error: You need the MAME source in the $srcdir/src/ directory" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 	if test ! -f $srcdir/src/advance.pat ; then
-		{ { echo "$as_me:$LINENO: error: You must patch the MAME source in src/ with the advance/advmame.dif patch" >&5
-echo "$as_me: error: You must patch the MAME source in src/ with the advance/advmame.dif patch" >&2;}
+		{ { echo "$as_me:$LINENO: error: You must patch the MAME source in $srcdir/src/ with the $srcdir/advance/advmame.dif patch" >&5
+echo "$as_me: error: You must patch the MAME source in $srcdir/src/ with the $srcdir/advance/advmame.dif patch" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 elif test $ac_with_emu = mess; then
 	if test ! -f $srcdir/srcmess/mame.mak ; then
-		{ { echo "$as_me:$LINENO: error: You need the MESS source in the srcmess directory" >&5
-echo "$as_me: error: You need the MESS source in the srcmess directory" >&2;}
+		{ { echo "$as_me:$LINENO: error: You need the MESS source in the $srcdir/srcmess/ directory" >&5
+echo "$as_me: error: You need the MESS source in the $srcdir/srcmess/ directory" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 	if test ! -f $srcdir/mess/mess.mak ; then
-		{ { echo "$as_me:$LINENO: error: You need the MESS source in the srcmess directory" >&5
-echo "$as_me: error: You need the MESS source in the srcmess directory" >&2;}
+		{ { echo "$as_me:$LINENO: error: You need the MESS source in the $srcdir/srcmess/ directory" >&5
+echo "$as_me: error: You need the MESS source in the $srcdir/srcmess/ directory" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 	if test ! -f $srcdir/srcmess/advance.pat ; then
-		{ { echo "$as_me:$LINENO: error: You must patch the MESS source in srcmess/ with the advance/advmess.dif patch" >&5
-echo "$as_me: error: You must patch the MESS source in srcmess/ with the advance/advmess.dif patch" >&2;}
+		{ { echo "$as_me:$LINENO: error: You must patch the MESS source in $srcdir/srcmess/ with the advance/advmess.dif patch" >&5
+echo "$as_me: error: You must patch the MESS source in $srcdir/srcmess/ with the advance/advmess.dif patch" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 elif test $ac_with_emu = pac; then
 	if test ! -f $srcdir/srcpac/mame.mak ; then
-		{ { echo "$as_me:$LINENO: error: You need the PacMAME source in the srcpac directory" >&5
-echo "$as_me: error: You need the PacMAME source in the srcpac directory" >&2;}
+		{ { echo "$as_me:$LINENO: error: You need the PacMAME source in the $srcdir/srcpac/ directory" >&5
+echo "$as_me: error: You need the PacMAME source in the $srcdir/srcpac/ directory" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 	if test ! -f $srcdir/srcpac/advance.pat ; then
-		{ { echo "$as_me:$LINENO: error: You must patch the PacMAME source in srcpac/ with the advance/advpac.dif patch" >&5
-echo "$as_me: error: You must patch the PacMAME source in srcpac/ with the advance/advpac.dif patch" >&2;}
+		{ { echo "$as_me:$LINENO: error: You must patch the PacMAME source in $srcdir/srcpac/ with the advance/advpac.dif patch" >&5
+echo "$as_me: error: You must patch the PacMAME source in $srcdir/srcpac/ with the advance/advpac.dif patch" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 elif test ! $ac_with_emu = none; then
@@ -3770,6 +4003,10 @@ echo "$as_me: error: The touch program is required for compressing" >&2;}
 
 fi
 CONF_COMPRESS=$ac_enable_compress
+
+UPX=$UPX
+
+TOUCH=$TOUCH
 
 
 # Check whether --enable-asm or --disable-asm was given.
@@ -4384,6 +4621,8 @@ s,@host@,$host,;t t
 s,@host_cpu@,$host_cpu,;t t
 s,@host_vendor@,$host_vendor,;t t
 s,@host_os@,$host_os,;t t
+s,@ASMFLAGS@,$ASMFLAGS,;t t
+s,@CFLAGS_BUILD@,$CFLAGS_BUILD,;t t
 s,@EXE@,$EXE,;t t
 s,@CONF_HOST@,$CONF_HOST,;t t
 s,@EXE_BUILD@,$EXE_BUILD,;t t
@@ -4401,15 +4640,22 @@ s,@ac_ct_CC@,$ac_ct_CC,;t t
 s,@INSTALL_PROGRAM@,$INSTALL_PROGRAM,;t t
 s,@INSTALL_SCRIPT@,$INSTALL_SCRIPT,;t t
 s,@INSTALL_DATA@,$INSTALL_DATA,;t t
+s,@LN_S@,$LN_S,;t t
 s,@AR@,$AR,;t t
 s,@ac_ct_AR@,$ac_ct_AR,;t t
 s,@RC@,$RC,;t t
 s,@ac_ct_RC@,$ac_ct_RC,;t t
+s,@RM@,$RM,;t t
+s,@CP@,$CP,;t t
+s,@MKDIR@,$MKDIR,;t t
+s,@ECHO@,$ECHO,;t t
 s,@TAR@,$TAR,;t t
 s,@GZIP@,$GZIP,;t t
+s,@ZIP@,$ZIP,;t t
 s,@ASM@,$ASM,;t t
 s,@CC_BUILD@,$CC_BUILD,;t t
 s,@CXX_BUILD@,$CXX_BUILD,;t t
+s,@ZLIBS@,$ZLIBS,;t t
 s,@CONF_EMU@,$CONF_EMU,;t t
 s,@SDLCONFIG@,$SDLCONFIG,;t t
 s,@SDLCFLAGS@,$SDLCFLAGS,;t t
@@ -4675,4 +4921,5 @@ fi
 echo "Compress executables :" $ac_enable_compress
 echo "Emulator debugger :" $ac_enable_debugger
 echo "CFLAGS :" $CFLAGS
+echo "LDFLAGS :" $LDFLAGS
 
