Commit

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2966,46 +2966,6 @@ fi
   test -n "$ZIP" && break
 done
 
-for ac_prog in nasm
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_ASM+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$ASM"; then
-  ac_cv_prog_ASM="$ASM" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_ASM="$ac_prog"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-fi
-fi
-ASM=$ac_cv_prog_ASM
-if test -n "$ASM"; then
-  echo "$as_me:$LINENO: result: $ASM" >&5
-echo "${ECHO_T}$ASM" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-  test -n "$ASM" && break
-done
-
 for ac_prog in gcc cc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -3617,6 +3577,52 @@ rm -f conftest.$ac_objext conftest.$ac_ext
 echo "${ECHO_T}$ac_enable_asm" >&6
 fi
 if test $ac_enable_asm = yes; then
+	for ac_prog in nasm nasmw
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_ASM+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$ASM"; then
+  ac_cv_prog_ASM="$ASM" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_ASM="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+ASM=$ac_cv_prog_ASM
+if test -n "$ASM"; then
+  echo "$as_me:$LINENO: result: $ASM" >&5
+echo "${ECHO_T}$ASM" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$ASM" && break
+done
+test -n "$ASM" || ASM="none"
+
+	if test $ASM = none; then
+		{ { echo "$as_me:$LINENO: error: The NASM assembler is required for the \"asm\" compilation" >&5
+echo "$as_me: error: The NASM assembler is required for the \"asm\" compilation" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
 	CFLAGS_ARCH="$CFLAGS_ARCH -DUSE_ASM_i586"
 fi
 
@@ -5021,13 +5027,13 @@ s,@ECHO@,$ECHO,;t t
 s,@TAR@,$TAR,;t t
 s,@GZIP@,$GZIP,;t t
 s,@ZIP@,$ZIP,;t t
-s,@ASM@,$ASM,;t t
 s,@CC_BUILD@,$CC_BUILD,;t t
 s,@CXX_BUILD@,$CXX_BUILD,;t t
 s,@ZLIBS@,$ZLIBS,;t t
 s,@CONF_DEBUG@,$CONF_DEBUG,;t t
 s,@CONF_CFLAGS_OPT@,$CONF_CFLAGS_OPT,;t t
 s,@CONF_LDFLAGS@,$CONF_LDFLAGS,;t t
+s,@ASM@,$ASM,;t t
 s,@CONF_CFLAGS_ARCH@,$CONF_CFLAGS_ARCH,;t t
 s,@CONF_EMU@,$CONF_EMU,;t t
 s,@SDLCONFIG@,$SDLCONFIG,;t t
